repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--ignore-init-module-imports",
            "--recursive",
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=100
          - --target-version=py38

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-bandit
          - flake8-blind-except
          - flake8-docstrings
          - flake8-logging-format
          - flake8-print

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
      - id: pyupgrade

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.931
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - pydantic
  #         - types-geoip2
  #         - sqlalchemy-stubs
  #         - types-pytz
  #         - types-redis
  #         - types-PyYAML
  #         - types-aiofiles
