name: "FaceDetection"
platform: "tensorrt_plan"
max_batch_size: 4
dynamic_batching { }
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "num_dets"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "det_boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4 ]
  }
]
output [
  {
    name: "det_scores"
    data_type: TYPE_FP32
    dims: [ 100 ]
  }
]
output [
  {
    name: "det_classes"
    data_type: TYPE_INT32
    dims: [ 100 ]
  }
]
output [
  {
    name: "det_lmks"
    data_type: TYPE_FP32
    dims: [ 100, 10 ]
  }
]
instance_group [
  {
    kind: KIND_GPU
  }
]
